{{- if .Values.ingressEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.app }}.{{ .Values.branch | default "default" }}.{{ .Values.domain | default "mdefenders.org" }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app }}
            port:
              number: {{ .Values.servicePort | default 80 }}
{{- end }}